/usr/bin/sqlite3 AuctionBase < create.sql
/usr/bin/sqlite3 AuctionBase < load.txt
/usr/bin/sqlite3 AuctionBase < constraints_verify.sql
/usr/bin/sqlite3 AuctionBase < trigger1_add.sql
/usr/bin/sqlite3 AuctionBase < trigger2_add.sql
/usr/bin/sqlite3 AuctionBase < trigger3_add.sql
/usr/bin/sqlite3 AuctionBase < trigger4_add.sql
/usr/bin/sqlite3 AuctionBase < trigger5_add.sql
/usr/bin/sqlite3 AuctionBase < trigger6_add.sql
/usr/bin/sqlite3 AuctionBase < trigger7_add.sql
/usr/bin/sqlite3 AuctionBase < trigger8_add.sql
